[versions]
agp = "8.9.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
kotlin = "2.2.21"
kotlinx-serialization-json = "1.9.0"
kotlinx-coroutines = "1.10.2"
maplibre = "12.3.0"
maplibre-geojson = "7.0.0-pre0"
coreKtx = "1.17.0"
annotationJvm = "1.9.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
maplibre = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }
maplibre-geojson = { group = "org.maplibre.gl", name = "geojson", version.ref = "maplibre-geojson" }
maplibre-geojson-turf = { group = "org.maplibre.gl", name = "turf", version.ref = "maplibre-geojson" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.3.10" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

